### ISSUE TITLE
WiFi mapping

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#10]
The WFA has  begun to recommend that Wi-Fi devices use the mapping in RFC8325.

**Comment by gorryfair** [comment]
Do we include this after the UP-mapping?

**Comment by gorryfair** [comment]
Not sure what WiFi Alliance spec to ref? - But the announcement is repeated here:
https://www.gotostage.com/channel/5fa21bd7e98e42d78e2b7ca5c3511712/recording/e56b98ee46534887870f68cca05e8548/watch

**Comment by ana-cc** [comment]
done and ref added
