### ISSUE TITLE
 S5.1.1: add in 802.1Q,

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#100]
"The mapping specified in [IEEE-802-1Q] revises a previous standard [IEEE-802-1D], in an effort to align with DiffServ practice [RFC4594]. The traffic types are specified to match the first three bits of a suitable DSCP (e.g., the first three bits of the EF DSCP are mapped to a PCP of 5)."

This paragraph is still ambiguous as to whether the second sentence refers to 1Q or 1D. Just adding "In 802.1Q, ..." would get the job done.

**Comment by ana-cc** [comment]
Closed in PR
