### ISSUE TITLE
2 NiTs in  S5.1.2:

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#101]
"Most current WiFi implementations [RFC8325] use a default mapping that maps the first three bits of the DSCP to the 802.11 UP value."

1. The 8325 citation here is misleading; it makes the reader think that 8325 mandates the default mapping, which it doesn't. Please delete the reference.

2. "RFC8325 also recommends a mapping in the upstream direction that derives the DSCP from the value of the UP multiplied by 8. This mapping can result in a specific DSCP remarking behavior."

s/RFC8325 also recommends/For other UPs, RFC8325 recommends

**Comment by ana-cc** [comment]
Removed the ref and updated the second sentence in PR
