### ISSUE TITLE
Grammar fixes - Lars

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#107]
#### Section 4, paragraph 2
```
e DSCP field to any value different than 0b000 (replace the 3 bits of the fo
                                    ^^^^
```
Did you mean "different from"? "Different than" is often considered colloquial
style. [DIFFERENT_THAN] (Also elsewhere.)

#### Section 4.2.2, paragraph 5
```
stems and subnetworks can, and do, utilise the DiffServ field in an IP packet
                                   ^^^^^^^
```
Do not mix variants of the same word ("utilise" and "utilize") within a single
text. [EN_WORD_COHERENCY] (Also elsewhere.)

#### Section 4.3, paragraph 2
```
E Ethernet 802.1Q header, the 3-bit WiFi UP field or the 3-bit Traffic Class
                                    ^^^^
```
Did you mean "Wi-Fi"? (This is the officially approved term by the Wi-Fi
Alliance.). [WIFI] (Also elsewhere.)

**Comment by gorryfair** [comment]
In this particular Section 4.3, paragraph 2, I'd remove the "wifi" .

Elsewhere we should check the use of Wi-Fi.
