### ISSUE TITLE
Clarify reference to RFC 2475

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#16]
4.  Remarking the DSCP

........Furthermore, RFC 2475 states that

[RG] Should read "RFC 2474" (the link of the html version is correct).

**Comment by RudiGe** [comment]
That's the one with "my typo comment" again...I think, it's best top drop it, I couldn't find any nit or typo and links were correct. Sorry.

**Comment by ana-cc** [comment]
Thank you very much for the input, closing
