### ISSUE TITLE
Clarify "non-DiffServ aware" terminology

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#18]
4.2.2.  Impact of ToS Precedence Remarking

    A less common remarking, ToS Precedence Remarking sets the first
    three bits of the DSCP to a non-zero value corresponding to a CS PHB.
    This remarking is distinctive of non-DiffServ aware routers.

[RG] Unfortunately, the draft doesn't inform the reader how the authors conclude that the PHB assigned after and the resulting forwarding is "non-DiffServ aware". The latter term isn't defined by the draft and no reference is given.

**Comment by RudiGe** [comment]
To me, a "non-DiffServ aware router" is not the same as a "router performing Non-diffserv aware remarking". Please clarify this terminology throughout the document. 
I understand your comment above. I still think, the text of the draft is ambiguous, at least.

**Comment by ana-cc** [comment]
We think this is now addressed in https://github.com/uoaerg/draft-tsvwg-dscp-considerations/pull/38/files

Thanks for your help!

**Comment by gorryfair** [comment]
Thanks
