### ISSUE TITLE
Redefine service class using an existing term

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#27]
Service Classes that can utilise existing PHBs should use assigned
     DSCPs to mark their traffic: Could the request be met by using an
     existing IETF DSCP?  The proposed new treatment be used to map
     traffic to a new or existing PHB.

[RG]: I can't parse the last sentence, please reword.
Suggested new first sentence: If an existing PHB is suitable to forward 
the traffic of your application, use an assigned DSCP. 
Please define "Service Classes" or provide a reference, if you continue to use this term.

**Comment by gorryfair** [comment]
/service class/ is defined in various RFCs with relation to a diffserv node. Text will be updated to clarify each time whether the term refers to a node or a domain.
