### ISSUE TITLE
RFC 4594 recommendations

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#42]
Something like: RFC 4594 recommended a local use of DSCPs 000xx1 binary. RFC 8436 changed the IANA registration policy of Pool 3, xxxx01 binary to assignment by Standards Action, this pool includes DSCP 1 [REF: LE PHB] and DSCP 5 [Ref NQB ID].

**Comment by gorryfair** [comment]
MD: Does the ID need to contain a section that explicitly updates RFC 4594 use, now we have passed the transition period?

**Comment by gorryfair** [comment]
Since the LE PHB - RFC 8622 updated 4594, I suggest we simply state this and suggest any future allocation of DSCP 5 would similarly update 4594 in PR https://github.com/uoaerg/draft-tsvwg-dscp-considerations/pull/48 . Is this sufficient?

**Comment by ana-cc** [comment]
PR looked great. Closing
