### ISSUE TITLE
Fix terminology and tenses

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#57]
Nit: Avoid use of future tense.

OLD

   Hex values will be represented in text using prefix

   0x.  Binary values will use prefix 0b.

NEW

   Hex values are represented in the following text using prefix

   0x.  Binary values use prefix 0b.

**Comment by gorryfair** [comment]
resolved in https://github.com/uoaerg/draft-tsvwg-dscp-considerations/pull/71
