### ISSUE TITLE
Avoid giving the impression that all observed pathologies are  consistent with, compliant with, and/or motivated by the Diffserv architecture

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#59]
This section’s classification of observed remarking behaviors is very useful, however the first two paragraphs leave the impression that all of these behaviors are consistent with, compliant with, and/or motivated by the Diffserv architecture, which is sometimes the case … and sometimes is not.  A sentence ought to be added to the “Reports measuring …” paragraph to indicate that there are a variety of reasons for the observed behaviors, some of which are not part of Diffserv functionality.

In the figure at the top of p.11, “Used by SSH” and “Future NQB” ought to be removed … particularly as the current NQB draft is no longer using DSCP 5. The mention of the use of DSCP 4 by SSH in the text that follows the figure is fine, and could even be reworked as a footnote to the table in the figure.

**Comment by gorryfair** [comment]
done in PR.
