### ISSUE TITLE
Change "behaviour" to "model" when discussing MPLS

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#60]
“behaviors” is not the right word – those are models, specifically Tunnel Models (in RFC 3270) or Tunnel Conceptual Models (if RFC 2983 terminology is used).

I hope Ruediger has carefully checked section 5.2 – there may be other MPLS-related concerns.

**Comment by gorryfair** [comment]
PR #68
