### ISSUE TITLE
Clarify last section of 4.2.2 - example remarking by ToS Precedence Bleach

### ISSUE THREAD

**Issue by ana-cc** [uoaerg/draft-tsvwg-dscp-considerations#67]
If remarking occurs, packets are forwarded using the PHB specified for the resulting DSCP in that domain.  For example, the AF31 DSCP (0x1a) could be remarked to either AF11 or AF21. As this packet further traverses other domains, it will receive treatment  as specified by the domain's operator corresponding to the remarked codepoint.

**Comment by gorryfair** [comment]
Done in PR
