### ISSUE TITLE
MD: IPv6

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#86]
COMMENTS:
- I found it odd to read this document and not see 'IPv6' anywhere. Are the antiquated equipment behaviors mitigated by IPv6, does it not matter, or do we not have data? A statement on this would be useful.

**Comment by gorryfair** [comment]
... do we have data we could use to say something and possibly cite?

**Comment by ana-cc** [comment]
Our journal paper that we cite throughout the draft examined both IPv4 and IPv6 routers. I think we just need a sentence to say this.

**Comment by gorryfair** [comment]
OK - please do add this sentence. 
I'll also add a sentence upfront to say Differentiated Services is defined for both IPv4 and IPv6, and DSCPs apply to both network protocols. When classifying traffic to set the DS field, IPv6 can also include the flow label.

**Comment by gorryfair** [comment]
Seems fixed now - the flow label wasn;t mentioned, too fine a level really for DSCPs. So PR now looks good.
