### ISSUE TITLE
Ref format S5.1.2:

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#87]
- S5.1.2:
"The recommendation [in RFC8325] includes mapping network control traffic CS6 and CS7, as well unassigned DSCPs, to UP 0."

**Comment by ana-cc** [comment]
From section 5.1 of RFC 8325: 

Note that it is explicitly stated that packets requesting a marking of CS6 or CS7 DSCP SHOULD be mapped to UP 0

From

**Comment by gorryfair** [comment]
The only issue I saw was the "in" inside the citation itself.

**Comment by ana-cc** [comment]
should we say RFC8325 recommends different markings depending on direction? UP 0 upstream (section 5.1), and UP 7 downstream (section 4.1).

**Comment by gorryfair** [comment]
So does this look like something like:

`~The marking recommendation in RFC8325 depends on the direction in which thew packet is forwarded. UP 0 is recommended for forwarding upstream (section 5.1), and UP 7 for forwarding downstream (section 4.1).

**Comment by gorryfair** [comment]
I finally proposed adjusted text in the PR

**Comment by gorryfair** [comment]
We failed to fix all tagged lines in -10. We should have searched for (/ also and checked for more!

**Comment by gorryfair** [comment]
Resoved in new PR
