### ISSUE TITLE
Cross reference to pathologies

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#89]
- There are numerous artifacts in the text that appear to be some sort of markup tag for section references, e.g. /Remark/, /Bleach/. Please clean these up or clarify the notation you're using.

**Comment by gorryfair** [comment]
What do you think? 
Now the document is fimnished, we could easily just refer directly to the relevent section, e.g. something like:

remarking according to ToS precedence (/Remark-ToS/)
becomes:
remarking according to ToS precedence, Remark-ToS, (described in this section)
etc

===


resulting DSCP when ToS Precedence Bleaching (/Bleach-ToS-Precedence/
   and /Bleach-some-ToS/) 
could be:
resulting DSCP when ToS Precedence Bleaching (Bleach-ToS-Precedence described in section xxx
   and Bleach-some-ToS described in section XX) 

===

What do you think?

**Comment by ana-cc** [comment]
Sounds good, happy to take this one

**Comment by gorryfair** [comment]
Addressed in PR
